apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: function
  namespace: invocation
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        qpoption.knative.dev/flow-config-allowed_json_flows: |-
          [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "function:knative", "value": {"operation": "f1"}}]}]
        qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/atnog/poliflow-evaluation/invocation/sample-function
