# apiVersion: v1
# kind: Namespace
# metadata:
#   name: refund
# ---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.20.1
    app.quarkus.io/commit-id: 214abb116b80978479a0106d78a90d5ce3212565
    app.quarkus.io/vcs-uri: https://github.com/ATNoG/knative-argo-workflows-apps-kit.git
    app.quarkus.io/build-timestamp: 2025-09-22 - 16:27:58 +0000
  labels:
    app.kubernetes.io/name: workflow
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: workflow
  namespace: refund
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-view
  namespace: refund
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: workflow
    namespace: refund
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.20.1
    app.quarkus.io/commit-id: 214abb116b80978479a0106d78a90d5ce3212565
    app.quarkus.io/vcs-uri: https://github.com/ATNoG/knative-argo-workflows-apps-kit.git
    app.quarkus.io/build-timestamp: 2025-09-22 - 16:27:58 +0000
  labels:
    app.kubernetes.io/name: workflow
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: workflow
  namespace: refund
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containers:
        - image: ghcr.io/atnog/poliflow-evaluation/refund/workflow:latest
          imagePullPolicy: Always
          name: workflow
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
      serviceAccountName: workflow
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: database-trigger-workflow
  namespace: refund
spec:
  broker: broker
  filters:
    - any:
        - exact:
            type: order.database.result
        - exact:
            type: info.database.result
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: workflow
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: http-request-received-trigger-workflow
  namespace: refund
spec:
  broker: broker
  filter:
    attributes:
      type: http.request.received
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: workflow
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: sb-workflow
  namespace: refund
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
      namespace: refund
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: workflow
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: broker
  namespace: refund
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: knative-eventing
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: entry-point
  namespace: refund
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containers:
        - image: ghcr.io/atnog/poliflow-evaluation/refund/entry-point
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: f1
  namespace: refund
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        qpoption.knative.dev/flow-config-allowed_json_flows: | 
          [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}]}]
        qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/atnog/poliflow-evaluation/refund/sample-function
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: f2
  namespace: refund
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        qpoption.knative.dev/flow-config-allowed_json_flows: | 
          [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "function:knative", "value": {"operation": "f1"}}, {"type": "event", "value": {"trigger": {"name": "getOrder", "type": "order.database.get", "kind": "produced"}, "result": {"name": "resultOrder", "source": "database-dummy", "type": "order.database.result", "kind": "consumed"}}}]}]
        qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/atnog/poliflow-evaluation/refund/sample-function
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: f3
  namespace: refund
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        qpoption.knative.dev/flow-config-allowed_json_flows: | 
          [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "function:knative", "value": {"operation": "f1"}}, {"type": "event", "value": {"trigger": {"name": "getOrder", "type": "order.database.get", "kind": "produced"}, "result": {"name": "resultOrder", "source": "database-dummy", "type": "order.database.result", "kind": "consumed"}}}, {"type": "function:knative", "value": {"operation": "f2"}}]}]
        qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/atnog/poliflow-evaluation/refund/sample-function
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: f4
  namespace: refund
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        qpoption.knative.dev/flow-config-allowed_json_flows: | 
          [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "function:knative", "value": {"operation": "f1"}}, {"type": "event", "value": {"trigger": {"name": "getOrder", "type": "order.database.get", "kind": "produced"}, "result": {"name": "resultOrder", "source": "database-dummy", "type": "order.database.result", "kind": "consumed"}}}, {"type": "function:knative", "value": {"operation": "f2"}}, {"type": "function:knative", "value": {"operation": "f3"}}, {"type": "event", "value": {"trigger": {"name": "emitRefund", "type": "info.database.emitRefund", "kind": "produced"}, "result": {"name": "resultRefund", "source": "database-dummy", "type": "info.database.result", "kind": "consumed"}}}]}]
        qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/atnog/poliflow-evaluation/refund/sample-function
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: database-dummy
  namespace: refund
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        qpoption.knative.dev/flow-config-type: event
        qpoption.knative.dev/flow-config-allowed_json_flows: | 
          [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "function:knative", "value": {"operation": "f1"}}]}, {"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "function:knative", "value": {"operation": "f1"}}, {"type": "event", "value": {"trigger": {"name": "getOrder", "type": "order.database.get", "kind": "produced"}, "result": {"name": "resultOrder", "source": "database-dummy", "type": "order.database.result", "kind": "consumed"}}}, {"type": "function:knative", "value": {"operation": "f2"}}, {"type": "function:knative", "value": {"operation": "f3"}}]}]
        qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/atnog/poliflow-evaluation/refund/database-dummy
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: result
  namespace: refund
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        qpoption.knative.dev/flow-config-allowed_json_flows: | 
          [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "function:knative", "value": {"operation": "f1"}}, {"type": "event", "value": {"trigger": {"name": "getOrder", "type": "order.database.get", "kind": "produced"}, "result": {"name": "resultOrder", "source": "database-dummy", "type": "order.database.result", "kind": "consumed"}}}, {"type": "function:knative", "value": {"operation": "f2"}}, {"type": "function:knative", "value": {"operation": "f3"}}, {"type": "event", "value": {"trigger": {"name": "emitRefund", "type": "info.database.emitRefund", "kind": "produced"}, "result": {"name": "resultRefund", "source": "database-dummy", "type": "info.database.result", "kind": "consumed"}}}, {"type": "function:knative", "value": {"operation": "f4"}}]}]
        qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/atnog/poliflow-evaluation/refund/result
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  generation: 1
  name: bind-entry-point
  namespace: refund
spec:
  sink: 
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
      namespace: refund
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: entry-point
    namespace: refund
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: database-dummy-trigger
  namespace: refund
spec:
  broker: broker
  filters:
    - any:
        - exact:
            type: order.database.get
        - exact:
            type: info.database.emitRefund
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: database-dummy
